# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 # source 'https://github.com/gumlet/gumlet-insights-sdk-avplayer.git'

target 'InsightsDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InsightsDemoApp
  
  pod 'GumletInsightsSDKAVPlayer', '~>1.0.0'

end
